sudo: true
language: rust
rust:
- nightly
- 1.0.0
- 1.2.0
script:
- cargo build
- cargo test
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc  &&
  echo '<meta http-equiv=refresh content=0;url=pusher/index.html>' > target/doc/index.html &&
  pip install --user ghp-import &&
  /home/travis/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${TOKEN}@github.com/pusher/pusher-http-rust.git gh-pages &&
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/pusher-*
env:
  global:
    secure: KUk/+ETCqM9CY/Qd+S9iVyFplBfPBVl8bwLGud2va3vAQilD78/ZMmd3FUA1yKXC2xbcIosu4UPquen8LlewSCpHHQqDmaR9d532nurxMQXcMYCU1ZQ0Kd2thdykabi38v5/IsqrgN1KZ4uRkE2GZ78yeFpQeXiAlxk/3sWWru2Al8muTn9RIZmtq0PzvUO1Gak7oJSsjT4b3fayoBQXVkIaR3F+i/ZR+ZfnojmY25r0dakk2dnODKpHetuPu4eFyF6ruSzI1ycCyRPHI/AjwvXkBfNOWig9Hu3mbMhDs7CUIGVPeiMyD5s/xs8+IJS5/2qVPvlcC5PubFkTNI5r9xa3iSx45pFv7Vh8SDf0FyUCwABuNWKby9SoT3B5TZkv+2lm6D9g7sIt5T4CVO7+7TpwNcqI6uqd+jChiFtXMrCvG8HFMieWJJWxWosbp5plsi4P5B3U+9G/ZpbqmHFFrLUFDRuh5qswi2ztkcoJFXP8Je88sPEIZRuIfElO48CEaDQuUjo1CG2/HwkrFBiLJObZ62CYZrXacB8JHmp/TX0laODEl82qCu53VxhJ6GtusFablDXTbeuEN6li5qIbPI9gnieh2R6/FU/d/8QT8kxttnGQOylFspe+/aOpByLq15Rsx5Rt8I2mkcbVqux0Htm57quRKZnG5hwycbmFju8=
